POST http://localhost:8080/bookSummaries
Content-Type: application/json

{
  "bookTitle": "Deep Work By Cal Newport",
  "chapterSummaries": [
    {
      "title": "Deep Work is Valuable",
      "summary": "In this chapter..."
    },
    {
      "title": "Bla bla bla",
      "summary": "Alooooo"
    }
  ]
}

###
