POST http://localhost:8080/bookSummaries
Content-Type: application/json

{
  "bookTitle": "Manual do Dev Eficiente",
  "chapterSummaries": [
    {
      "title": "Escreva só o necessário",
      "summary": "Aqui........ resumo....",
      "chapterOrder": 1
    },
    {
      "title": "Só implemente o que foi pedido",
      "summary": "Não implemente..............................",
      "chapterOrder": 2
    }
  ]
}

###
